euroleague_api_config:
  box_score_base_url: "https://live.euroleague.net/api/Boxscore"
  box_score_queries:
    - ["E2017", "240"]
    - ["E2018", "240"]
    - ["E2019", "252"]
    - ["E2020", "306"]
    - ["E2021", "210"]
    - ["E2022", "306"]
    - ["E2023", "306"]
    - ["E2024", "252"]